# Wrapper Makefile so STM32CubeIDE's "Existing Code as Makefile Project"
# import succeeds. All real work is delegated to CMake via the build/Debug
# tree generated by `cmake --preset Debug`.
#
# CubeIDE invokes `make all` for build, `make clean` for clean.

BUILD_DIR := build/Debug

.PHONY: all clean rebuild flash configure

all:
	cmake --build $(BUILD_DIR)

clean:
	cmake --build $(BUILD_DIR) --target clean

rebuild: clean all

# One-time (or after CMakeLists.txt changes): regenerate the build tree.
configure:
	cmake --preset Debug

# Convenience flash via STM32_Programmer_CLI (matches .vscode/tasks.json).
flash: all
	"C:/ST/STM32CubeCLT_1.21.0/STM32CubeProgrammer/bin/STM32_Programmer_CLI.exe" \
	    -c port=SWD mode=UR reset=HWrst \
	    -d $(BUILD_DIR)/Software_Hybrid.elf -rst
