/*
 * fc_link_task.c — DroneCAN gateway between Pixhawk FC and PCU.
 *
 * - Owns the single CanardInstance — no other task touches libcanard.
 * - RX: every CAN1 frame is fed to canardHandleRxFrame; complete transfers
 *   land in on_transfer_received, which decodes ThrottleDemand and updates
 *   FC liveness on uavcan.protocol.NodeStatus.
 * - TX: PTConcise @ 20 Hz, NodeStatus @ 1 Hz, drained from libcanard's
 *   internal queue into can_mgr_send.
 * - FC-loss policy: NodeStatus silent > 1 s -> raise FAULT_FC_STALE.
 *
 * Codec headers below are generated by dronecan_dsdlc — see README in
 * Middlewares/Third_Party/dronecan_codec/.
 */

#include "fc_link_task.h"

/* Compile to a no-op stub when the auto-generated DroneCAN codecs and
 * libcanard haven't been dropped in yet. Once you run dronecan_dsdlc and
 * place canard.c/h, the next build picks up the real implementation
 * automatically — no edits to this file or freertos.c needed. */
#if __has_include("canard.h") && __has_include("dsdl.lat.powertrain.PTConcise.h")

#include "can_manager.h"
#include "powertrain_state.h"
#include "sensor_task.h"
#include "canard.h"
#include "dsdl.lat.powertrain.PTConcise.h"
#include "dsdl.lat.powertrain.ThrottleDemand.h"
#include "uavcan.protocol.NodeStatus.h"

#include "cmsis_os2.h"
#include "FreeRTOS.h"
#include "task.h"
#include <string.h>

#define FC_LINK_PERIOD_MS         50            /* 20 Hz tick */
#define FC_LINK_HEARTBEAT_MS    1000            /* 1 Hz NodeStatus */
#define FC_LINK_PT_PERIOD_MS      50            /* 20 Hz PTConcise */
#define FC_LINK_FC_STALE_MS     1000            /* declare FC lost */

#define FC_LINK_RX_QUEUE_DEPTH    32
#define FC_LINK_MEM_POOL_BYTES  2048

static StaticTask_t       s_tcb;
static StackType_t        s_stack[512];          /* 2 KB */

static StaticQueue_t      s_rxq_cb;
static can_frame_t        s_rxq_items[FC_LINK_RX_QUEUE_DEPTH];
static osMessageQueueId_t s_rx_q;

static uint8_t            s_mem_pool[FC_LINK_MEM_POOL_BYTES];
static CanardInstance     s_canard;

static uint8_t            s_tid_pt     = 0;
static uint8_t            s_tid_status = 0;

static volatile uint32_t  s_fc_last_status_tick = 0;     /* 0 = never */

/* --- libcanard callbacks ------------------------------------------------ */

static bool should_accept(const CanardInstance *ins,
                          uint64_t              *out_signature,
                          uint16_t               data_type_id,
                          CanardTransferType     transfer_type,
                          uint8_t                source_node_id) {
    (void)ins; (void)source_node_id;
    if (transfer_type != CanardTransferTypeBroadcast) return false;

    if (data_type_id == DSDL_LAT_POWERTRAIN_THROTTLEDEMAND_ID) {
        *out_signature = DSDL_LAT_POWERTRAIN_THROTTLEDEMAND_SIGNATURE;
        return true;
    }
    if (data_type_id == UAVCAN_PROTOCOL_NODESTATUS_ID) {
        *out_signature = UAVCAN_PROTOCOL_NODESTATUS_SIGNATURE;
        return true;
    }
    return false;
}

static void on_transfer_received(CanardInstance    *ins,
                                 CanardRxTransfer  *transfer) {
    (void)ins;
    if (transfer->transfer_type != CanardTransferTypeBroadcast) return;

    if (transfer->data_type_id == DSDL_LAT_POWERTRAIN_THROTTLEDEMAND_ID) {
        struct dsdl_lat_powertrain_ThrottleDemand msg;
        /* dronecan_dsdlc decoder returns false on success. */
        if (!dsdl_lat_powertrain_ThrottleDemand_decode(transfer, &msg)) {
            /* DSDL flight_phase enum is identical to vesc_mode_t. */
            vesc_mode_t mode  = (vesc_mode_t)msg.flight_phase;
            uint16_t    thr   = (uint16_t)(msg.throttle_pct * 100.0f);
            if (thr > 10000) thr = 10000;
            pt_set_fc_inputs(mode, thr);
        }
    }
    else if (transfer->data_type_id == UAVCAN_PROTOCOL_NODESTATUS_ID) {
        s_fc_last_status_tick = osKernelGetTickCount();
        pt_clear_fault(FAULT_FC_STALE);
    }
}

/* --- TX side ------------------------------------------------------------ */

static void publish_pt_concise(void) {
    powertrain_state_t pt;
    osMutexAcquire(g_pt_mtx, osWaitForever);
    pt = g_pt;
    osMutexRelease(g_pt_mtx);

    struct dsdl_lat_powertrain_PTConcise msg;
    msg.egu_ok           = !(pt.fault_bits & (FAULT_RECT_OFFLINE | FAULT_BUS2_BUSOFF));
    msg.batt_ok          = (pt.bms_soc_pct > 1000);                   /* SOC > 10 % — placeholder */
    msg.v_bus            = pt.rect_state.V_dc_cV   / 100.0f;
    msg.i_load           = 0.0f;                                      /* TODO: from ADS1262 once front-end is final */
    msg.i_bat            = 0.0f;                                      /* TODO: from BMS task once it exists */
    msg.i_rect           = pt.rect_state.I_dc_cA   / 100.0f;
    msg.batt_soc         = pt.bms_soc_pct          / 100.0f;
    msg.fuel_consumption = 0.0f;                                      /* TODO: from ECU CAN feed */

    uint8_t buf[DSDL_LAT_POWERTRAIN_PTCONCISE_MAX_SIZE];
    uint32_t len = dsdl_lat_powertrain_PTConcise_encode(&msg, buf);

    canardBroadcast(&s_canard,
                    DSDL_LAT_POWERTRAIN_PTCONCISE_SIGNATURE,
                    DSDL_LAT_POWERTRAIN_PTCONCISE_ID,
                    &s_tid_pt,
                    CANARD_TRANSFER_PRIORITY_MEDIUM,
                    buf, (uint16_t)len);
}

static void publish_node_status(uint32_t uptime_sec) {
    struct uavcan_protocol_NodeStatus msg;
    msg.uptime_sec                  = uptime_sec;
    msg.health                      = UAVCAN_PROTOCOL_NODESTATUS_HEALTH_OK;
    msg.mode                        = UAVCAN_PROTOCOL_NODESTATUS_MODE_OPERATIONAL;
    msg.sub_mode                    = 0;
    msg.vendor_specific_status_code = pt_get_faults();

    uint8_t buf[UAVCAN_PROTOCOL_NODESTATUS_MAX_SIZE];
    uint32_t len = uavcan_protocol_NodeStatus_encode(&msg, buf);

    canardBroadcast(&s_canard,
                    UAVCAN_PROTOCOL_NODESTATUS_SIGNATURE,
                    UAVCAN_PROTOCOL_NODESTATUS_ID,
                    &s_tid_status,
                    CANARD_TRANSFER_PRIORITY_LOW,
                    buf, (uint16_t)len);
}

static void drain_canard_tx(void) {
    const CanardCANFrame *frame;
    while ((frame = canardPeekTxQueue(&s_canard)) != NULL) {
        can_frame_t f;
        f.id  = frame->id & CANARD_CAN_EXT_ID_MASK;
        f.ext = (frame->id & CANARD_CAN_FRAME_EFF) ? 1 : 0;
        f.rtr = (frame->id & CANARD_CAN_FRAME_RTR) ? 1 : 0;
        f.dlc = frame->data_len;
        memcpy(f.data, frame->data, frame->data_len);
        if (can_mgr_send(CAN_BUS_DRONECAN, &f, 0)) {
            canardPopTxQueue(&s_canard);
        } else {
            break;                                    /* HW + SW queue full — retry next tick */
        }
    }
}

/* --- Task --------------------------------------------------------------- */

static void fc_link_task(void *arg) {
    (void)arg;
    uint32_t boot           = osKernelGetTickCount();
    uint32_t last_pt_tx     = boot;
    uint32_t last_status_tx = boot;
    uint32_t next           = boot;

    for (;;) {
        uint32_t now = osKernelGetTickCount();

        /* RX: hand every frame to libcanard (timestamp in microseconds). */
        can_frame_t f;
        while (osMessageQueueGet(s_rx_q, &f, NULL, 0) == osOK) {
            CanardCANFrame cf;
            cf.id       = f.id
                        | (f.ext ? CANARD_CAN_FRAME_EFF : 0)
                        | (f.rtr ? CANARD_CAN_FRAME_RTR : 0);
            cf.data_len = f.dlc;
            cf.iface_id = 0;
            memcpy(cf.data, f.data, f.dlc);
            (void)canardHandleRxFrame(&s_canard, &cf, (uint64_t)now * 1000ULL);
        }

        if (now - last_pt_tx >= FC_LINK_PT_PERIOD_MS) {
            publish_pt_concise();
            last_pt_tx = now;
        }
        if (now - last_status_tx >= FC_LINK_HEARTBEAT_MS) {
            publish_node_status((now - boot) / 1000u);
            last_status_tx = now;
        }

        if (s_fc_last_status_tick &&
            (now - s_fc_last_status_tick) > FC_LINK_FC_STALE_MS) {
            pt_set_fault(FAULT_FC_STALE);
        }

        drain_canard_tx();
        canardCleanupStaleTransfers(&s_canard, (uint64_t)now * 1000ULL);

        next += FC_LINK_PERIOD_MS;
        osDelayUntil(next);
    }
}

void fc_link_task_start(void) {
    static const osMessageQueueAttr_t qattr = {
        .name    = "fc_rxq",
        .cb_mem  = &s_rxq_cb,
        .cb_size = sizeof(s_rxq_cb),
        .mq_mem  = s_rxq_items,
        .mq_size = sizeof(s_rxq_items),
    };
    s_rx_q = osMessageQueueNew(FC_LINK_RX_QUEUE_DEPTH,
                               sizeof(can_frame_t), &qattr);

    /* Subscribe to ALL extended-frame traffic on CAN1; libcanard's
     * shouldAcceptTransfer filters by DTID. One filter bank consumed. */
    can_mgr_subscribe(CAN_BUS_DRONECAN, 0u, 0u, true, s_rx_q);

    canardInit(&s_canard, s_mem_pool, sizeof(s_mem_pool),
               on_transfer_received, should_accept, NULL);
    canardSetLocalNodeID(&s_canard, FC_LINK_NODE_ID);

    static const osThreadAttr_t tattr = {
        .name       = "fc_link",
        .cb_mem     = &s_tcb,
        .cb_size    = sizeof(s_tcb),
        .stack_mem  = s_stack,
        .stack_size = sizeof(s_stack),
        .priority   = osPriorityAboveNormal,           /* prio 4 */
    };
    osThreadNew(fc_link_task, NULL, &tattr);
}

#else  /* codecs / libcanard not yet present */

void fc_link_task_start(void) { /* stub — no-op until codecs are generated */ }

#endif
